pipeline:
  build:
    image: docker
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    commands:
     - docker build -t mnwalalm/example-webserver:$DRONE_COMMIT_SHA .
  
  test:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker run mnwalalm/example-webserver:$DRONE_COMMIT_SHA /test.sh
      
  push:
    image: docker
    environment:
      - PASS=${HUB_PASS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker login -u mnwalalm -p $PASS
      - docker push mnwalalm/example-webserver:$DRONE_COMMIT_SHA
      
  deploy:
    image: docker
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    commands:
     - docker pull mnwalalm/example-webserver:$DRONE_COMMIT_SHA
     - docker tag  mnwalalm/example-webserver:$DRONE_COMMIT_SHA mnwalalm/example-webserver:latest
     - docker stack deploy -c ./docker-compose.yml example-webserver